In [4]:
import pandas as pd
import json

In [5]:
results_dir = '../evaluating_responses/part_1/'
results_dirc = '../evaluating_responses/part_1c/'

In [13]:
o3mini = pd.read_csv(results_dir+'o3-mini_corrected.csv')
o3mini.groupby(['Culture', 'Size', 'Remarks']).mean(['Blocking_Pair_Count'])

                                      Instance  Correctness  \
Culture     Size Remarks
ic          10   Processed smoothly.      24.5         1.00
            20   Processed smoothly.      24.5         0.68
            50   Processed smoothly.      24.5         0.00
womanmaster 10   Processed smoothly.      24.5         1.00
            20   Processed smoothly.      24.5         0.80
            50   Processed smoothly.      24.5         0.00

                                      Blocking_Pair_Count  Jaccard_Similarity  \
Culture     Size Remarks
ic          10   Processed smoothly.                 0.00            1.000000
            20   Processed smoothly.                 1.22            0.841769
            50   Processed smoothly.               180.04            0.120479
womanmaster 10   Processed smoothly.                 0.00            1.000000
            20   Processed smoothly.                 0.32            0.943610
            50   Processed smoothly.               174.62            0.393051

                                      Intersection
Culture     Size Remarks
ic          10   Processed smoothly.         10.00
            20   Processed smoothly.         17.90
            50   Processed smoothly.         10.52
womanmaster 10   Processed smoothly.         10.00
            20   Processed smoothly.         19.34
            50   Processed smoothly.         26.68

In [14]:
def JSONMatchToList(json_match_string):
    json_match_string = json_match_string.replace(" ", "")
    if json_match_string.endswith("],]"):
        pairs = json_match_string[1:-2].split('],[')
    else:
        pairs = json_match_string[1:-1].split('],[')
    
    # print("IN JSON TO STR FUNC")
    # print(pairs)

    # Step 2: Extract the W number from each pair and convert to integer
    result = []
    for pair in pairs:
        # Split the pair and take the second element (Wj), then extract the number
        w_value_str = (pair.split(',')[1][1:])
        if w_value_str[-1] == "]":
            if w_value_str[-2] == "]":
                w_value = int(w_value_str[:-2])
            else:
                w_value = int(w_value_str[:-1])
        else:
            w_value = int(w_value_str)
        result.append(w_value)

    # Step 3: Print the resulting list
    return result
    # print(result)  # Output: [7, 2, 9, 5, 4, 1, 6, 8, 10, 3]

def JSONobjToList(json_obj, n):
    if not json_obj:
        print("EMPTY JSON OBJ")
        return [], 'empty'
    matching = []
    for m in range(1, n+1):
        mstring = f"M{m}"
        if mstring not in json_obj or not json_obj[mstring] or json_obj[mstring].lower().strip() == 'none':
            matching.append(0)
        else:
            try:
                woman = int(json_obj[mstring][1:])
                matching.append(woman)
            except:
                print(f"WRONG VALUE FORMAT: {json_obj[mstring]}")
                return matching, f"For example, {mstring}'s match is given the incorrect format - {json_obj[mstring]}. "
    return matching, "okay"

same, total = 0, 0
for row in o3mini.values:
    culture = row[0]
    size = row[1]
    instance = row[2]
    answer, verdict = JSONobjToList(json.loads(row[3].replace('\'', '\"')), size)
    correctness = row[4]
    if correctness == 0: continue
    instance_data = pd.read_csv(f'../instances_matchings/{size}_{culture}_processed.csv')
    men_opt = JSONMatchToList(instance_data['men_opt'].values[instance])
    same += int(answer == men_opt)
    total += 1
    if answer != men_opt:
        print(culture, size, instance)
        print(answer)
        print(men_opt)

ic 20 4
[6, 11, 20, 1, 10, 5, 3, 8, 14, 17, 13, 9, 7, 19, 12, 16, 15, 2, 4, 18]
[6, 20, 4, 1, 10, 5, 19, 8, 14, 17, 7, 11, 3, 9, 12, 16, 15, 2, 13, 18]
ic 20 24
[20, 12, 18, 4, 6, 3, 16, 1, 19, 5, 13, 11, 8, 10, 9, 14, 15, 7, 17, 2]
[20, 17, 18, 4, 6, 3, 16, 1, 19, 5, 13, 11, 8, 10, 9, 14, 15, 7, 12, 2]

In [15]:
print(same, total)

172 174

In [8]:
o3mini = pd.read_csv(results_dirc+'o3-mini_corrected.csv')
o3mini.head()

,Culture,Size,Instance,Corrected,Correctness,Blocking_Pair_Count,Blocking_Pair_List,Jaccard_Similarity,Intersection,Remarks
0,womanmaster,50,0,"{'W1': 'T48', 'W2': 'T10', 'W3': 'T40', 'W4': ...",0,41,"[[6, 10], [6, 39], [6, 14], [6, 16], [6, 7], [...",0.666667,40,Processed smoothly.
1,womanmaster,50,1,"{'W1': 'T38', 'W2': 'T27', 'W3': 'T26', 'W4': ...",1,0,[],1.000000,50,Processed smoothly.
2,womanmaster,50,2,"{'W1': 'T1', 'W2': 'T2', 'W3': 'T3', 'W4': 'T4...",0,486,"[[1, 5], [1, 12], [1, 16], [1, 13], [2, 11], [...",0.020408,2,Processed smoothly.
3,womanmaster,50,3,"{'W1': 'T10', 'W2': 'T26', 'W3': 'T13', 'W4': ...",0,17,"[[26, 25], [30, 27], [30, 7], [31, 34], [31, 4...",0.612903,38,Processed smoothly.
4,womanmaster,50,4,"{'W1': 'T8', 'W2': 'T45', 'W3': 'T38', 'W4': '...",0,128,"[[17, 1], [22, 1], [24, 41], [27, 45], [27, 13...",0.136364,12,Processed smoothly.

In [12]:
o3mini.groupby(['Culture', 'Size', 'Remarks']).mean(['Blocking_Pair_Count'])

                                      Instance  Correctness  \
Culture     Size Remarks
ic          10   Processed smoothly.      24.5         0.98
            20   Processed smoothly.      24.5         0.50
            50   Processed smoothly.      24.5         0.00
womanmaster 10   Processed smoothly.      24.5         1.00
            20   Processed smoothly.      24.5         0.72
            50   Processed smoothly.      24.5         0.02

                                      Blocking_Pair_Count  Jaccard_Similarity  \
Culture     Size Remarks
ic          10   Processed smoothly.                 0.02            0.985000
            20   Processed smoothly.                 1.74            0.802552
            50   Processed smoothly.               172.58            0.123410
womanmaster 10   Processed smoothly.                 0.00            1.000000
            20   Processed smoothly.                 0.40            0.930762
            50   Processed smoothly.               275.50            0.317384

                                      Intersection
Culture     Size Remarks
ic          10   Processed smoothly.          9.88
            20   Processed smoothly.         17.40
            50   Processed smoothly.         10.68
womanmaster 10   Processed smoothly.         10.00
            20   Processed smoothly.         19.20
            50   Processed smoothly.         20.14

In [10]:
def JSONMatchToList(json_match_string):
    json_match_string = json_match_string.replace(" ", "")
    if json_match_string.endswith("],]"):
        pairs = json_match_string[1:-2].split('],[')
    else:
        pairs = json_match_string[1:-1].split('],[')
    
    # print("IN JSON TO STR FUNC")
    # print(pairs)

    # Step 2: Extract the W number from each pair and convert to integer
    result = []
    for pair in pairs:
        # Split the pair and take the second element (Wj), then extract the number
        w_value_str = (pair.split(',')[1][1:])
        if w_value_str[-1] == "]":
            if w_value_str[-2] == "]":
                w_value = int(w_value_str[:-2])
            else:
                w_value = int(w_value_str[:-1])
        else:
            w_value = int(w_value_str)
        result.append(w_value)

    # Step 3: Print the resulting list
    return result
    # print(result)  # Output: [7, 2, 9, 5, 4, 1, 6, 8, 10, 3]

def JSONobjToList(json_obj, n):
    if not json_obj:
        print("EMPTY JSON OBJ")
        return [], 'empty'
    matching = []
    for m in range(1, n+1):
        mstring = f"W{m}"
        if mstring not in json_obj or not json_obj[mstring] or json_obj[mstring].lower().strip() == 'none':
            matching.append(0)
        else:
            try:
                woman = int(json_obj[mstring][1:])
                matching.append(woman)
            except:
                print(f"WRONG VALUE FORMAT: {json_obj[mstring]}")
                return matching, f"For example, {mstring}'s match is given the incorrect format - {json_obj[mstring]}. "
    return matching, "okay"

same, total = 0, 0
for row in o3mini.values:
    culture = row[0]
    size = row[1]
    instance = row[2]
    answer, verdict = JSONobjToList(json.loads(row[3].replace('\'', '\"')), size)
    correctness = row[4]
    if correctness == 0: continue
    instance_data = pd.read_csv(f'../instances_matchings/{size}_{culture}_processed.csv')
    men_opt = JSONMatchToList(instance_data['men_opt'].values[instance])
    same += int(answer == men_opt)
    total += 1
    if answer != men_opt:
        print(culture, size, instance)
        print(answer)
        print(men_opt)

ic 10 1
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[2, 7, 6, 1, 9, 4, 3, 5, 10, 8]

In [11]:
print(same, total)

160 161